project_management/site_completeness_checklist copy.md
- removes duplicate testing blocks
@robtarr or @cromwellryan can you review quickly? :eyes:
=> feat: add favicon generator

SUMMARY.md, build_process/README.md, build_process/general.md, build_process/node.md
To reduce cognitive overhead in project switching, we should standardize a set of npm scripts to use for common tasks in all our projects.
=> Documentation for standard npm scripts to use across projects

style/README.md, style/pattern_libraries/README.md
This adds a new section for pattern libraries.
It also adds some documentation for how we currently build pattern libraries.
=> chore: add pattern library documentation.

culture/README.md, services/slack/README.md
Update the "Slack" section with the channel guidelines we have stored (until now) in Google Docs.
=> docs: Update 'Slack' with channel guidelines

project_management/README.md
Wrong "cues" in project_management/README.md
=> fix: Correct usage of "cues" in PM section

software/README.md, software/apache/README.md
This brings in the [Apache setup instructions](https://github.com/sparkbox/craft#sparkbox---craft) which originated in sparkbox/craft into the standard and makes it cohesive with the `laptop` script by relying on it's Homebrew and MySQL installs.
=> Apache setup for local development

services/harvest/README.md
Added "Sparkbox employees only" so as to not confuse the public why they can't access a private doc in a public repo.
=> Forecast FAQs with additional content description

software/apache/README.md
Apache will throw an error if you try to start it with an empty `vhost` folder. This is a suggestion for fixing that, totally open to other suggestions.
=> docs: Update apache instructions

software/apache/README.md
I fixed a few typos and a broken link. 
I had a question about this part:
> Important file locations:
/usr/local/etc/php/5.6/php.ini
/usr/local/etc/php/7.0/php.ini
Should we explain why these are important?
=> docs: fix typos and CMS projects link

software/apache/README.md
Update apache project root example to reflect the existing seesparkbox root.
Since we link to this doc in the seesparkbox setup docs (and already use seesparkbox as an example in the doc), it's nice to have the correct project root to plug into the `.conf` file we make.
=> docs: update apache project root example

README.md, software/README.md, software/cms/README.md
A few sections seemed to be unlinked, relying solely on clickthrough of folders.
- Add hosting and office sections to main readme
- Connect Platforms to Services/CMS (I'm not sure if this was the best way to do that)
=> 📝docs: update table of contents and link cms docs together

services/harvest/README.md
Adding the info on how to setup HH:MM format on 2017 and up laptops. 
Using getharvest app for mac.
=> docs: 2018 update for harvest time format

software/apache/README.md
To resolve this notice, encountered after running `sudo apachectl -k restart` setting up seesparkbox on a new laptop:
[Tue Sep 18 10:56:15.729649 2018] [proxy_html:notice] [pid 82201] AH01425: I18n support in mod_proxy_html requires mod_xml2enc. Without it, non-ASCII characters in proxied pages are likely to display incorrectly.
=> feat: Enable I18n support for non-ASCII characters

SUMMARY.md, build_process/htaccess_snippets.md, project_management/site_completeness_checklist.md
This adds a .md file with the .htaccess snippets for allowing users on the Sparkbox network to directly access password protected QA sites. It also adds an entry in the Site Completeness Checklist for adding this to a QA site and a link to the snippets. I also took the opportunity here to add a direct link to the Site Completeness Checklist from the Summary, just to make it easier to find.
=> Add .htaccess snippets for QA sites

culture/remote/README.md
Gitlab is an all remote company and has written a great "manifesto" explaining how they do remote work. We can reference this as Sparkbox evolves it's own remote culture.
=> docs(remote): References Gitlab's All Remote culture resource

code-style/git/README.md
* Add that we now use JIRA prefixes and card numbers in branch names and commit messages
* Reorder the sections so that at the top it's an overview, and as you go down the document it gets more specific
* Adjust links and documentation to adhere to that top > down flow
* Add "additional resources section" that links to foundry articles
Filtering by commits will really help validate this card. 634213c (first), 98ec6fa (third), and 557d55b (fourth) are the commits in which I actually changed information in the doc. db84deb (second) is the commit where all I did was change the order of the information.
=> feat: add jira connection info, refactor: top down approach to flow

services/slack/README.md
This small PR fixes the spelling of Slack in the .md file.
=> docs: Fix spelling of Slack in markdown.

security/verified-commits.md
Add a paragraph to the security: verified commits documentation based on personal experience.
=> docs(security): add documentation on expired gpg keys

README.md, apprenticeship/README.md, culture/knowledge-sharing/README.md
This is the first of a few steps to migrate the apprenticeship curriculum into the standard.
Your audience:
- New hires and current Sparkbox employees
- New clients via proposal documents
Unlike Foundry articles, these contributions are being created directly in Github, not in google docs.
**The goal for this first effort is to:** 
The general structure we’re looking to create is **what→ why→ how**. This means it will start with what our process is from a high-level view. Then it will move on to the rationale for why this topic is important to Sparkbox and why we have come to the conclusions we have about it. Then it will dive down into a more detailed, task-based description of what we do, likely using bullet points or numbered lists.
These are some general writing guidelines to …
=> Add Apprentice Curriculum

accessibility/introduction/README.md, how-we-work-together.md
Fix some minor spelling and formatting issues.
=> Minor spelling and formatting fixes

security/linux-policy-checks.sh
This adds a script similar to the existing policy script that tries to check for encrypted drives and software updates for Linux. This assumes the user is using the `apt` package manager.
=> add linux policy script

security/security_policy_compliance/README.md
Since the production branch has changed from `master` to `main`, we need to update the path to the policy checks shell script.
1. Using your eyeballs, confirm that the path to the `policy-checks.sh` file reflects the `main` branch instead of the `master` branch.
=> docs: Update path for the `policy-checks` command

build_process/dev-tools.md
Update reference to `sass` package since `node-sass` has officially been deprecated.
=> feat: Update node-sass to sass

security/security_policy_compliance/policy-checks.sh
This reflects a hardware/continuity policy change that makes backups optional.
When Time machine backups are not configured, the lack of volume encryption is expected... there are no backup volumes to encrypt.
To test this:
1. Run the `policy-script.sh` while backups are configured and the drive is connected. You should expect a ✅  for an encrypted backup volume.
2. Eject the same volume and run the script. You should get a "⚠️".
3. In time machine preferences, disable time machine by Removing the disk. Run the script and you should get a ✅  saying "Backups not configured."
=> 🔐  Backups are optional

security/security_policy_compliance/windows-policy-checks.ps1
adds a security compliance script similar to the existing mac and linux scripts, but for windows. this is a powershell script that checks for windows updates, bitlocker status, and windows defender status.
=> feat: add windows policy script

code-style/git/README.md
This pull request is to add language about commit history curation to the Git document. Explaining this process will help newcomers to Sparkbox better understand the philosophy and intentions behind pull requests and peer reviews, and how to ensure these interactions are both efficient and helpful.
=> docs: Add language about commit history curation

README.md, accessibility/introduction/README.md, build_process/drops.md, career/tech-lead-role.md, code-style/code_reviews/README.md, code-style/git/PULL_REQUEST_TEMPLATE.md, code-style/git/README.md, code-style/pattern_libraries/README.md, code-style/scss/README.md, culture/remote/README.md, development_process/README.md, how-we-work-together.md, naming_conventions/servers.md, office/email-signature.md, platforms/cms.md, project_management/base-hub.md, project_management/site_completeness_checklist.md, services/slack/README.md, software/README.md, web-fundamentals/README.md
In working through our onboarding materials I noticed links in the standard to `https://seesparkbox.com` were not redirecting appropriately. 
To Address this:
- replaced links going to `seesparkbox.com` with `sparkbox.com` 
- updated references to `seesparkbox.com` to `sparkbox.com` where appropriate (email-signature, cms, site_completeness_checklist, servers)
- The #sparkbox-com slack channel has been notified about redirect issue
**Note:** I did not change the use of seesparkbox.com with in the link to the github repo for sparkbox.com, I do not have access to this repo so I was not able to confirm that the repo name is still seesparkbox, let me know if it has changed to sparkbox and I can adjust. 
`https://github.com/sparkbox/seesparkbox.com/blob/labs-addition/static/data/labs/page-data. …
=> fix: replaces seesparkbox with sparkbox

security/security_policy_compliance/policy-checks.sh
Updates the security script output to only consider minor/patch updates required. Security patches are typically patch fixes. Major OS updates are not required for security compliance.
1. Check out this branch
2. Download [test.patch.gz](https://github.com/sparkbox/standard/files/11023519/test.patch.gz)
3. Run `gunzip test.patch.gz && git apply test.patch` to apply testing patch. This reads a mock `test.txt` file instead of running the actual `softwareupdate` command.
4. `test.txt` includes 3 updates:
- A software update (Safari)
- A MacOS patch version update
- A MacOS major version update
6. Run `./security/security_policy_compliance/policy-checks.sh`
7. The output should show:
- A **recommendation** to upgrade the major OS version
- A **requirement** to update OS from `12.6.2` to …
=> feat: make only minor and patch OS updates required in security policy script

security/security_policy_compliance/mac-updates.md
When you use the _copy_ button, it copies everything, including the `$`. If you paste that into the command line, you get an error, because `$` is not a command. By dropping it, you should be able to hit the _copy_ button and paste the command directly into your command line without a problem.
=> fix: drop $ from sudo softwareupdate line
