sparkbox/standard

style/README.md, style/non-code/README.md
=> feat: add email signature settings

office/printer.md
This was surprisingly painful to find.
@cromwellryan
=> feat: Adding link to printer setup doc

culture/food-and-drink/README.md, culture/how-we-play/README.md
READMEs were in the wrong place. 😄
=> :bug: fix: swap README contents in food-and-drink and how-we-play

project_management/README.md
Start of an update to achieve @cromwell happiness
=> wip: Update README.md

style/all_code/README.md
=> feat (Style): Adding a little fun to the code style page

SUMMARY.md, almanac/IE9.md, almanac/README.md
This provides a way for us to document browser bugs by browser. I'm totally open to how we should organize or maintain this.
=> start almanac

SUMMARY.md, almanac/general.md
=> add position:fixed + transform interaction

README.md
=> chore: update links in the README

security/verified-commits.md
@cromwellryan / @yock look good?
=> add instructions for using gpg-verification repo

hosting/README.md, naming_conventions/servers.md
* Added a new folder for naming conventions
* Created a new document with recommendation for server naming conventions
=> Naming conventions

code-style/git/README.md, project_management/site_completeness_checklist.md
Several of our recent projects have had problem with CSS or Javascript changes deploying to production because of browser caching. We should have some kind of automated cache busting process in place to prevent these problem in the future. Add this to the Site Completeness Checklist.
Also, fixed a URL I noticed.
=> Add cache busting

software/apache/README.md
Originates in https://github.com/sparkbox/craft/commit/b0adc35e1782cfc09dd1cba3cc2025e421a111e7
=> Brew's apache is now much simpler

services/harvest/README.md
Added a brief sentence description with a link to our Harvest & Forecast FAQs
=> Adding Forecast FAQs

platforms/cms.md, platforms/craftcms.md, platforms/drupal.md
=> WIP: Choosing a CMS platform

project_management/site_completeness_checklist.md
At this point, the existence of Github Checklists is a known
feature.
=> Devops Section

README.md, laptop/README.md
Maintenance was spelled wrong - updated 🤓
=> fix: spelling error

security/README.md, security/policy-checks.sh
This will check for the MacOS specific items in the list.
=> Policy check shell script for file vault and updates

code-style/git/README.md
New section on branch naming conventions.
=> feat: branch naming convention

code-style/git/ISSUE_TEMPLATE.md, code-style/git/PULL_REQUEST_TEMPLATE.md, code-style/git/README.md
Added a section to the git readme referencing PR templates, as well as an example template in a .md file.
=> feat (code-style/git): Add example PR & Issue templates

code-style/ruby/README.md
Replaces the placeholder text with a brief summary.
=> docs: Add summary for ruby code style

code-style/code_reviews/README.md, code-style/rails/README.md, culture/README.md
Updates some old (or unnecessary) language and adds a few helpful links.
(A few of these were items in @catheraaine's slack note. I crossed them off!)
=> Minor content updates for rails, ruby, and code reviews

security/devices.md
* Added info for iPhone X or newer users @ Sparkbox
=> docs: added info for options for Face ID

code-style/markdown/README.md
Erring on the side of tone police.
=> fix(codestyle/markdown): change language to be more inclusive

culture/README.md, culture/remote/README.md
This remote work section is a starting point of information gathering to help our team work with remote peers more effectively.
=> feat(culture): add remote work section

code-style/all_code/README.md, package-lock.json
- Updates general guidelines for code style
=> docs(185): updates general code style

almanac/IE11.md
=> :memo: add focus svg attribute

code-style/git/PULL_REQUEST_TEMPLATE.md
The list of browsers to test was over a year old. Made minor updates to better encompass current lists, mostly Safari.
=> feat(code style / git): Update Browser Testing list in PR Template example.

design/README.md
This adds a section for Design. This centers around design tools we use and why we use them. It's geared for new hires, to quickly get them up to speed.
https://docs.google.com/document/d/1htzj1c_vAVhXqcTykYja98DPs6aEb4KObcMIx2dAKN0/edit?usp=sharing
=> docs: add section on design tools

laptop/README.md
I feel pretty good about all the sections except the one on "Wiping a Laptop." I think those instructions are old (I recently wiped a laptop and I don't think I used a bootable drive).
@asimpson, can you help me put together some updated instructions on that? I've forgotten some of the details, from when you walked me through it last time.
=> docs: update the section on laptop maintenance

accessibility/introduction/README.md
Creates new Accessibility portion of the standard as part of my thought leadership contribution! 
Here is the original google doc: https://docs.google.com/document/d/1Tf2JqsIytATTgFwQIP5_Mk_DjNDySekCbC4PXdKcIHA/edit?ts=5dbb36ba#heading=h.thlw0ke3w27i
=> docs: adds accessibility portion of standard

build_process/package-management.md
=> feat: add section on package management

design/README.md, design/design-design_reviews.md, design/design-design_tools.md, design/design-file_organization.md, design/design-foundry_image_guidelines.md
Adding individual files for design reviews, foundry image guidelines, file organization.
=> Design content additions

code-style/git/PULL_REQUEST_TEMPLATE.md
"Effect" is a noun. "Affect" is a verb.
=> Docs: Fix grammar issue in PR Template

software/ssh/README.md
Adds two sections: 
- Using an SSH config file / Creating Identity Files
- Debugging SSH
Adds updates suggested from Naomi to the existing section.
=> docs: Add IdentifyFile + Debug docs to ssh

code-style/git/PULL_REQUEST_TEMPLATE.md
A few fixes prompted from using this PR template on P&G.
=> docs: proofread pr template

README.md, hosting/README.md, platforms/hosting.md
Includes hosting categories, considerations for making a hosting decision, and examples of services we've used successfully in the past.
1. View [the markdown preview of the new page](https://github.com/sparkbox/standard/blob/docs--hosting-platforms/platforms/hosting.md).
2. Confirm that it renders correctly and makes sense.
=> Add a page for platforms/hosting

laptop/README.md
Improve instructions based on Dar's learning
=> Wiping a laptop

security/security_policy_compliance/timemachine.md
This updates documentation about optional backups for security policy.
=> Backups are optional

interviews/technical-exercises.md
We've found that tech exercise reviews can be inconsistent, because the need for both qualitative and quantitative feedback is not clear. This template should help bring clarity and consistency to the feedback.
=> Review template for reviewers

security/security_policy_compliance/devices.md
+ update android password setup to include pattern option
=> Add Section for Android Pattern Lock

security/security_policy_compliance/linux-policy-check.sh
- Also added a step to check Git GPG signing locally. We could break
this out for everyone if it's a popular enough idea.
=> feat: add nixos compatability to Linux script

code-style/git/PULL_REQUEST_TEMPLATE.md
This PR updates the PR section explanations to markdown comments instead of italicized text. By doing this, developers will no longer have to manually remove the section explanations before submitting the review to reduce unnecessary noise in the submitted PR.
=> Docs: Update PR Template

code-style/git/PULL_REQUEST_TEMPLATE.md
This PR fixes an issue where the PR Template had the incorrect instructions for the validation section.
=> Docs: Fix PR Template Instructions
